gcloud_data_path: ./gcloud-document
url: 
  - https://cloud.google.com/vertex-ai/docs/start/introduction-unified-platform
  - https://cloud.google.com/vertex-ai/generative-ai/docs/learn/overview
  - https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview
  - https://cloud.google.com/dialogflow/vertex/docs
  - https://cloud.google.com/vertex-ai/docs/start/introduction-unified-platform
  - https://cloud.google.com/dialogflow/docs/
  - https://cloud.google.com/dialogflow/cx/docs/basics
  - https://cloud.google.com/dialogflow/es/docs/basics
  - https://cloud.google.com/generative-ai-app-builder/docs/agent-intro
  - https://cloud.google.com/natural-language/docs/apis
  - https://cloud.google.com/discovery-engine/media/docs/introduction
  - https://cloud.google.com/retail/docs/features
  - https://cloud.google.com/generative-ai-app-builder/docs/introduction
  - https://cloud.google.com/text-to-speech/docs/how-to
  - https://cloud.google.com/text-to-speech/custom-voice/docs
  - https://cloud.google.com/video-intelligence/docs/quickstarts
  - https://cloud.google.com/vision-ai/docs/overview
  - https://cloud.google.com/colab/docs/introduction
  - https://developers.google.com/looker-studio/connector/get-started
  - https://developers.google.com/looker-studio/connector/reference
  - https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview
  - https://cloud.google.com/deep-learning-vm/docs/introduction
  - https://cloud.google.com/tpu/docs/v5p-training
  - https://cloud.google.com/compute/docs/instances
  - https://cloud.google.com/dataproc/docs/concepts/overview
  - https://cloud.google.com/tpu/docs/intro-to-tpu
  - https://cloud.google.com/deep-learning-containers/docs/getting-started-local
  - https://cloud.google.com/dialogflow/es/docs/video
  - https://cloud.google.com/contact-center/insights/docs
  - https://cloud.google.com/document-ai/docs/drag-and-drop
  - https://cloud.google.com/document-ai/docs/reference
  - https://cloud.google.com/document-ai/docs/samples/documentai-process-ocr-document?hl=en
  - https://cloud.google.com/architecture/data-mesh
  - https://cloud.google.com/architecture/reference-patterns/overview
  - https://cloud.google.com/dataflow/docs/overview
  - https://cloud.google.com/dataflow/docs/machine-learning
  - https://cloud.google.com/firestore/docs/overview
  - https://cloud.google.com/pubsub/docs/overview
  - https://cloud.google.com/pubsub/docs/samples/pubsub-commit-proto-schema
  - https://cloud.google.com/retail/docs/features
  - https://cloud.google.com/dataplex/docs/quickstart-guide
  - https://cloud.google.com/dataplex/docs/quickstart-guide
  - https://cloud.google.com/deploy/docs/overview
  - https://cloud.google.com/appengine/docs/standard
  - https://cloud.google.com/bare-metal/docs/bms-planning
  - https://cloud.google.com/batch/docs/get-started
  - https://cloud.google.com/compute/docs/instances
  - https://cloud.google.com/migration-center/docs/migration-center-overview
  - https://cloud.google.com/run/docs/overview/what-is-cloud-run
  - https://cloud.google.com/recommender/docs/whatis-activeassist
  - https://cloud.google.com/compute/shielded-vm/docs/shielded-vm
  - https://cloud.google.com/source-repositories/docs/quickstarts
  - https://cloud.google.com/build/docs/overview
  - https://cloud.google.com/artifact-registry/docs/docker/store-docker-container-images
  - https://cloud.google.com/artifact-analysis/docs/artifact-analysis
  - https://cloud.google.com/software-supply-chain-security/docs/overview
  - https://cloud.google.com/secure-source-manager/docs/overview
  - https://cloud.google.com/alloydb/docs/overview
  - https://cloud.google.com/spanner/docs/create-query-database-console
  - https://cloud.google.com/sql/docs/introduction
  - https://cloud.google.com/sql/docs/postgres/introduction
  - https://cloud.google.com/sql/docs/mysql/introduction
  - https://cloud.google.com/sql/docs/sqlserver/introduction
  - https://cloud.google.com/vmware-engine/docs/whats-new
  - https://cloud.google.com/telecom-subscriber-insights/docs/overview
  - https://cloud.google.com/intrusion-detection-system/docs/overview
  - https://cloud.google.com/nat/docs/overview
  - https://cloud.google.com/vpc-service-controls/docs/set-up-service-perimeter
  - https://cloud.google.com/firewall/docs/about-firewalls
  - https://cloud.google.com/secure-web-proxy/docs/initial-setup-steps
  - https://cloud.google.com/distributed-cloud/edge/latest/docs/overview
  - https://cloud.google.com/distributed-cloud/hosted/docs/latest/gdch/overview
  - https://cloud.google.com/apigee/docs/api-platform/get-started/what-apigee
  - https://cloud.google.com/build/docs/build-push-docker-image
  - https://cloud.google.com/distributed-cloud/docs
  - https://cloud.google.com/migrate/containers/docs/getting-started
  - https://cloud.google.com/service-health/docs/overview
  - https://cloud.google.com/deployment-manager/docs/manage-cloud-resources-deployment
  - https://cloud.google.com/cdn/docs/overview
  - https://cloud.google.com/media-cdn/docs/overview
  - https://cloud.google.com/transcoder/docs/transcode-video
  - https://cloud.google.com/video-stitcher/docs/quickstarts/inserting-ads-into-vod
  - https://cloud.google.com/livestream/docs/quickstarts/quickstart-dash
  - https://cloud.google.com/free/docs/free-cloud-features?hl=zh-tw
  - https://cloud.google.com/workstations/docs/create-workstation
  - https://cloud.google.com/iam/docs/grant-role-console
  - https://cloud.google.com/stackdriver/docs
  - https://cloud.google.com/telecom-subscriber-insights/docs/overview
  - https://cloud.google.com/healthcare-api/docs/store-healthcare-data-rest
  - https://cloud.google.com/shell/docs/quickstart
  - https://cloud.google.com/endpoints/docs
  - https://cloud.google.com/carbon-footprint/docs/view-carbon-data    