gcloud_data_path: ./gcloud-document
url: 
  - https://cloud.google.com/compute/docs/instances
  - https://cloud.google.com/storage/docs/discover-object-storage-console
  - https://cloud.google.com/sql/docs/introduction
  - https://cloud.google.com/firestore/docs/overview
  - https://cloud.google.com/memorystore/docs/cluster/memorystore-for-redis-cluster-overview