gcloud_data_path: ./gcloud-document
url: 
  - https://cloud.google.com/storage/docs/introduction
  - https://cloud.google.com/bigquery/docs/introduction
  - https://cloud.google.com/run/docs/overview/what-is-cloud-run
  - https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster
  - https://cloud.google.com/vertex-ai/docs
  - https://cloud.google.com/looker/docs/intro
  - https://cloud.google.com/apigee/docs/api-platform/get-started/what-apigee